project_name: supervisord

env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - CC=clang
  - CXX=clang++

before:
  hooks:
    - go mod download

builds:
  - id: static
    binary: supervisord
    env:
      - CGO_ENABLED=1
    ldflags:
      - >-
        {{ if eq .Os "linux" }} -linkmode external -extldflags -static {{ end }}
    flags:
      - -tags=release
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: archive_static
    builds: [static]
    name_template: >-
      {{ .ProjectName }}{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats: [ 'tar.gz' ]
    wrap_in_directory: true

release:
  github:
    owner: fred01
    name: supervisord
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
